package killerm.minecraft.communication;

import killerm.minecraft.commands.CommandType;
import killerm.minecraft.data.DiaConfig;
import killerm.minecraft.helper.CollectionDelimiter;
import killerm.minecraft.game.data.Team;

// Intentional code duplication and ugly inner class to increase readability
public class Message {
    public static final String GOLD = "§6";
    public static final String GREY = "§7";
    public static final String DARK_RED = "§4";
    public static final String RED = "§c";
    public static final String DARK_BLUE = "§1";
    public static final String AQUA = "§b";
    public static final String BLUE = "§9";
    public static final String GREEN = "§a";
    public static final String DARK_AQUA = "§3";
    public static final String BOLD = "§l";
    public static final String STRIKE = "§m";
    public static final String ITALIC = "§o";
    public static final String RESET = "§r";
    public static final String TEAM_AQUA = BLUE;
    public static final String TEAM_LAVA = RED;

    public static final String PREFIX_BROADCAST = AQUA + BOLD + "◆Dia Hunt◆ " + DARK_AQUA;
    public static final String PREFIX_BROADCAST_ERROR = PREFIX_BROADCAST + DARK_RED + "ERROR: " + DARK_AQUA;
    public static final String PREFIX_TELL = AQUA + BOLD + "◆ " + GREY;
    public static final String PREFIX_TELL_ERROR = PREFIX_TELL + RESET + DARK_RED + "ERROR: " + GREY;

    public static final String COLLECTION_DELIMITER = ", ";
    public static final String VALID_COMMANDTYPES = "Valid commands: " + CollectionDelimiter.delimit(CommandType.values(), CommandType::toString);
    public static final String COMMANDTYPE_NOT_VALID = "This command isn't valid! " + VALID_COMMANDTYPES;
    public static final String COMMAND_NOT_IMPLEMENTED = "This command hasn't been implemented yet!";
    public static final String VALID_DIACONFIGS = "Valid configurations: " + CollectionDelimiter.delimit(DiaConfig.values(), DiaConfig::toString);
    public static final String DIACONFIG_NOT_VALID = "This configuration isn't valid! " + VALID_DIACONFIGS;
    public static final String DIACONFIG_NOT_IMPLEMENTED = "This command hasn't been implemented yet!";
    public static final String DESCRIPTION_EMPTY = "";
    public static final String DESCRIPTION_CONFIG = "Change config values. Usage: /diahunt config KEY <value>";
    public static final String DESCRIPTION_START = "Start a Dia Hunt game. Usage: /diahunt play <Player1> <Player2> ..";
    public static final String DESCRIPTION_JOIN = "Join a Dia Hunt game. Usage: /diahunt join <Team>";
    public static final String DESCRIPTION_LEAVE = "Leave a Dia Hunt game. Usage: /diahunt leave";
    public static final String DESCRIPTION_STOP = "Stop a Dia Hunt game. Usage: /diahunt stop";
    public static final String DESCRIPTION_STATUS = "Show current game status and Player in game. Usage: /diahunt status";

    public static final String VALID_TEAMS = "Valid teams: " + CollectionDelimiter.delimit(Team.values(), Team::toString);
    public static final String TEAM_NOT_VALID = "This team isn't valid! " + VALID_TEAMS;
    public static final String IS_SET_TO = " is set to ";
    public static final String CONFIG_LOCATION_INDICATOR = "location";
    public static final String TOO_MANY_ARGS = "You entered too many arguments!";
    public static final String AND = " and ";
    public static final String NOT_SAME_TYPE = " are not the same type!";
    public static final String SYMBOL_FIRE = "ᐃ";
    public static final String SYMBOL_WATER = "ᐁ";
    public static final String SPACE = " ";
    public static final String TABLE_DELIMITER = " | ";
    public static final String RIGHT_ARROW = "→";
    public static final String LEFT_ARROW = "←";
    public static final String JOINED_TEAM = " has joined team ";
    public static final String LEFT = " has left Dia Hunt!";
    public static final String ITEM_DIA_CHEST = AQUA + "Dia Chest";
    public static final String ITEM_DIAMOND = AQUA + "Diamond";
    public static final String COULD_NOT_RANDOM_PLAYER = "Couldn't generate random player because team ";
    public static final String IS_EMPTY = " is empty!";
    public static final String DIA_LINE = "◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆";
    public static final String GAME_STARTED_BY = "§lGame started by ";
    public static final String EXMARK = "!";
    public static final String YOU_ARE_INVITED = "You have been invited in a Dia Hunt game!";
    public static final String ACCEPT = "§a§l→JOIN←";
    public static final String HAVE_BEEN_INVITED = " have been invited";
    public static final String HAS_BEEN_INVITED = " has been invited";
    public static final String GAME_START_IN = "Game will start in ";
    public static final String SECONDS = " seconds!";
    public static final String START_DIA = "◆Start!◆";
    public static final String GET_DIAS = "Get all the diamonds!";
    public static final String GAME_STARTED = "DiaHunt has been started!";
    public static final String STOPPED = "Game has been stopped!";
    public static final String NOT_INGAME = "You are not ingame!";
    public static final String GAME_ALREADY_STARTING = "Game is already starting!";
    public static final String GAME_ALREADY_RUNNING = "Game is already running!";
    public static final String INVALID_GAME_STATUS = "Invalid game status!";
    public static final String NO_GAME_IN_PROGRESS = "No game in Progress!";
    public static final String IS_NO_PLAYER = " is not a valid player!";
    public static final String TOO_MANY_INPUTS = "Too many inputs!";
    public static final String PLAYER_NOT_FOUND = "Couldn't fix case of player!";
    public static final String NO_PLAYERS_LEFT = "There is no player left!";
    public static final String SYMBOL_DIAMOND = "◆";
    public static final String KILLED = " has completely destroyed ";
    public static final String HAS_DIED = " has died! Loser haha!";
    public static final String UNTIL_RESPAWN = "seconds until respawn";
    public static final String GO = "Go!";
    public static final String NEW_CONFIG_VALUE = "New config value has been set";
    public static final String DESCRIPTION_BUILDING = "Buy blocks to build bridges like a 12 year old!";
    public static final String DESCRIPTION_MELEE = "Buy melee weapons to f*** them at close range!";
    public static final String DESCRIPTION_RANGED = "Buy ranged weapon to camp and snipe them!";
    public static final String DESCRIPTION_EFFECTS = "Buy cool effects to dominate in every fight!";
    public static final String DESCRIPTION_PROTECTION = "Buy some lame protection!";
    public static final String DESCRIPTION_TRICKY = "Buy some cool items to outplay them!";
    public static final String SHOP_NAME = "Shop";
}